### ISSUE TITLE
Need to create a Project

### ISSUE THREAD

**Issue by fenwickjb** [JaysGitLab/cs-5666-greeting-mattstone22133#1]
Look near the top of the github window for the Projects tab (Code, Issues, Pull requests, Projects, ...)

Create a project and make a few columns: TODO, In Progress, Completed.

**Comment by fenwickjb** [comment]
Hoping this image comes through to show Project tab.
![github screenshot](http://cs.appstate.edu/~jbf/gitproj.png)

**Comment by matts-dev** [comment]
I believe I did what I was actually supposed to do this time. The image you responded with came through.
